[package]
name = "packet_capture"
version = "0.1.0"
authors = ["tanaka <tanaka.219.game@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = ""
